#!/bin/bash -e

case "$1" in
    configure)
		# if first install show message for initial configuration
        if [ -z "$2" ]; then
        	echo ""
			echo "================================================================================"
			echo "Percona Agent is installed but not configured and started."
			echo ""
			echo "Run the following command with root permissions to configure (replace values as needed):"
			echo "  percona-agent-installer -mysql-user=root -mysql-pass=mysql_root_pass -api-key=your_key_here"
			echo ""
			echo "To start the service run following:"
			echo "  service percona-agent start";
			echo "================================================================================"
			echo ""
        else
   		    # if upgrade start service
        	if which invoke-rc.d >/dev/null 2>&1; then
	     		invoke-rc.d percona-agent start
	     	else
	     		/etc/init.d/percona-agent start
	     	fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0